name: Daily Mailer

on:
  schedule:
    - cron: "33 1 * * *"   # Runs at 7:03 AM IST (1:33 AM UTC)
  workflow_dispatch:       # Allows manual run too

jobs:
  run-mailer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run mailer
        run: node app.cjs
